# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8621412511b0bb40c2bc36fc1415bf9ede4ff4d7729ee7e6d356cd33bf9f318b5aaabf7d98f4384c04daccca9285ce148ce0b737e46f2ef104a69af68be1794a

test:
  secret_key_base: 6395b0c38b92487536c79687d23dca951bbcef01012b5def168154a3751a2b98839ed0cb707bfdd5a1eb8461ed24d5ff3c7134915382515245d4f896b3eef21a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
